meta:
  service:
    username: (( vault $CREDENTIALS "/redis:username" ))
    password: (( vault $CREDENTIALS "/redis:password" ))

name: (( grab meta.params.name ))
director_uuid: (( grab meta.params.director_uuid ))

releases:
- name: redis
  version: 12

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3147

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: redis
  instances: 1
  azs: [z1]
  jobs:
  - name: redis
    release: redis
    properties:
      port: 3606
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  networks:
  - name: default
  properties:
    auth:
      username: (( grab meta.service.username ))
      password: (( grab meta.service.password ))
