---
meta:
  size: default
  default:
    az: z1
  password: (( vault $CREDENTIALS "/redis/system:password" ))

releases:
  - { name: redis-forge, version: latest }

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
  - name: standalone
    instances: 1
    azs: [(( grab meta.az || meta.default.az ))]
    networks: [name: (( grab meta.net || 'redis-service' ))]
    stemcell: default

    vm_type: (( grab meta.size ))
    persistent_disk: (( grab meta.disk || 0 ))

    jobs:
      - release: containers
        name:    docker
        properties:
          recipe:
            version: '3'
            services:
              redis:
                image: redis
                ports: ['6379:6379']
                command: [
                  - redis-server
                  - protected-mode
                  - 'no'
                  - --appendonly
                  - 'yes'
                  - --appendfilename
                  - redis.aof
                  - appendfsync
                  - everysec
                  - --requirepass
                  - (( grab meta.password ))
                volumes:
                  - '/var/vcap/store/redis:/data'
